// Measured from the real ZIP identity payloads. Used only for diagnostics; manifest hashes remain authoritative.

export const ACT_ONE_REQUIRED_PATHS: readonly string[] = [
  "Fichas de personagem/Ficha - Alan.jpg",
  "Fichas de personagem/Ficha - Edgar.jpg",
  "Fichas de personagem/Ficha - Eloísa.jpg",
  "Fichas de personagem/Ficha - Kênia.jpg",
  "Fichas de personagem/Ficha - Victor.jpg",
  "Handouts/Handout 01 - Conversa Eloísa.png",
  "Handouts/Handout 02 - Símbolo no Teto.jpg",
  "Handouts/Handout 03 - RG de Gustavo.jpg",
  "Handouts/Handout 04 - Anotações Arqueológicas.jpg",
  "Handouts/Handout 05A - Conversa Grupo.png",
  "Handouts/Handout 05B - Conversa Alan.png",
  "Handouts/Handout 05C - Conversa Victor.png",
  "Handouts/Handout 06 - Estante de Livros.jpg",
  "Handouts/Handout 07 - Pôster Lutadores de Rua.jpg",
  "Handouts/Handout 08 - Pôster Unidos do Invisível Futebol Clube.jpg",
  "Handouts/Handout 10 - Thunderland 2008.jpg",
  "Handouts/Handout 11 - RG de Alan.jpg",
  "Handouts/Handout 12A - E-mail de Gustavo 1.png",
  "Handouts/Handout 12B - Email de Gustavo 2.png",
  "Handouts/Handout 12C - E-mail de Gustavo 3.png",
  "Handouts/Handout 13 - Cadáver de Gustavo.jpg",
  "Handouts/Handout 14 - Foto de aniversário.jpg",
  "Handouts/Handout 9 - Pôster Eric Tufão 3 - A Explosão Explosiva.jpg",
  "Históricos de personagem/Histórico - Alan.jpg",
  "Históricos de personagem/Histórico - Edgar.jpg",
  "Históricos de personagem/Histórico - Eloísa.jpg",
  "Históricos de personagem/Histórico - Kênia.jpg",
  "Históricos de personagem/Histórico - Victor.jpg",
  "Mapas/Mapa 01 - O Porão.jpg",
  "Mapas/Mapa 02 - O Porão + Sala Secreta.jpg",
  "Mapas/Mapa 03 - O Porão + Sala Secreta + Duto de Ventilação (completo).jpg",
  "Músicas/Música 01 - O Porão.mp3",
  "Músicas/Música 02 - O Ídolo.mp3",
  "Tokens/Personagem - Alan.png",
  "Tokens/Personagem - Edgar.png",
  "Tokens/Personagem - Eloísa.png",
  "Tokens/Personagem - Kênia.png",
  "Tokens/Personagem - Victor.png",
  "Tokens/Token - Alan.png",
  "Tokens/Token - Edgar.png",
  "Tokens/Token - Eloísa.png",
  "Tokens/Token - Kênia.png",
  "Tokens/Token - Victor.png",
];

export const ACT_TWO_REQUIRED_PATHS: readonly string[] = [
  "Fichas e históricos de personagem/Ficha - Amanda.jpg",
  "Fichas e históricos de personagem/Ficha - Antônio.jpg",
  "Fichas e históricos de personagem/Ficha - Heitor.jpg",
  "Fichas e históricos de personagem/Ficha - Raven.jpg",
  "Fichas e históricos de personagem/Ficha - Val.jpg",
  "Fichas e históricos de personagem/Histórico - Amanda.jpg",
  "Fichas e históricos de personagem/Histórico - Antônio.jpg",
  "Fichas e históricos de personagem/Histórico - Heitor.jpg",
  "Fichas e históricos de personagem/Histórico - Raven.jpg",
  "Fichas e históricos de personagem/Histórico - Val.jpg",
  "Handouts/Handout 01 - Compendium Playtest para impressão.pdf",
  "Handouts/Handout 01 - Compendium Playtest preenchível.pdf",
  "Handouts/Handout 02A - Laser Porão.jpg",
  "Handouts/Handout 02B - Laser Sala Secreta.jpg",
  "Handouts/Handout 03 - Foto do Altar de Madeira.png",
  "Handouts/Handout 04 - Foto Dentro do Depósito B.png",
  "Handouts/Handout 05 - Ritual de Alterar Memória.jpg",
  "Handouts/Handout 06 - Foto do Freezer.png",
  "Mapa/Mapa 01 - O Porão.jpg",
  "Tokens/Personagem - Amanda.png",
  "Tokens/Personagem - Antônio.png",
  "Tokens/Personagem - Heitor.png",
  "Tokens/Personagem - Raven.png",
  "Tokens/Personagem - Val.png",
  "Tokens/Token - Amanda.png",
  "Tokens/Token - Antônio.png",
  "Tokens/Token - Heitor.png",
  "Tokens/Token - Raven.png",
  "Tokens/Token - Val.png",
];
