import type { AdventureDefinition } from "../../core/adventure-import/adventure-definition";

// References are the exact original ZIP entries, including their root folders.
// The official files are supplied by the user and are never bundled with the system.
export const PLAYTEST_ALPHA_ADVENTURE = {
  id: "playtest-alpha",
  packageIds: { actOne: "ato-i-extras", actTwo: "ato-ii-extras" },
  scenes: [{ presetId: "actOne.basement" }],
  actors: [
    { presetId: "actOne.kenia" },
    { presetId: "actOne.edgar" },
    { presetId: "actOne.alan" },
    { presetId: "actOne.eloisa" },
    { presetId: "actOne.victor" },
    { presetId: "actTwo.val" },
    { presetId: "actTwo.raven" },
    { presetId: "actTwo.antonio" },
    { presetId: "actTwo.amanda" },
    { presetId: "actTwo.heitor" },
  ],
  assets: [
    { id: "actOne.basement.map", kind: "map", label: "Porão", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Mapas/Mapa 01 - O Porão.jpg" } },
    { id: "actOne.basement.secretRoomMap", kind: "map", label: "Porão e sala secreta", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Mapas/Mapa 02 - O Porão + Sala Secreta.jpg" } },
    { id: "actOne.basement.completeMap", kind: "map", label: "Porão, sala secreta e duto", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Mapas/Mapa 03 - O Porão + Sala Secreta + Duto de Ventilação (completo).jpg" } },
    { id: "actOne.kenia.portrait", kind: "portrait", label: "Kênia — retrato", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Personagem - Kênia.png" } },
    { id: "actOne.kenia.token", kind: "token", label: "Kênia — token", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Token - Kênia.png" } },
    { id: "actOne.edgar.portrait", kind: "portrait", label: "Edgar — retrato", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Personagem - Edgar.png" } },
    { id: "actOne.edgar.token", kind: "token", label: "Edgar — token", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Token - Edgar.png" } },
    { id: "actOne.alan.portrait", kind: "portrait", label: "Alan — retrato", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Personagem - Alan.png" } },
    { id: "actOne.alan.token", kind: "token", label: "Alan — token", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Token - Alan.png" } },
    { id: "actOne.eloisa.portrait", kind: "portrait", label: "Eloísa — retrato", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Personagem - Eloísa.png" } },
    { id: "actOne.eloisa.token", kind: "token", label: "Eloísa — token", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Token - Eloísa.png" } },
    { id: "actOne.victor.portrait", kind: "portrait", label: "Victor — retrato", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Personagem - Victor.png" } },
    { id: "actOne.victor.token", kind: "token", label: "Victor — token", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Tokens/Token - Victor.png" } },
    { id: "actOne.handout.01", kind: "handout", label: "Handout 01 — conversa", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 01 - Conversa Eloísa.png" } },
    { id: "actOne.handout.02", kind: "handout", label: "Handout 02 — símbolo", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 02 - Símbolo no Teto.jpg" } },
    { id: "actOne.handout.03", kind: "handout", label: "Handout 03 — RG", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 03 - RG de Gustavo.jpg" } },
    { id: "actOne.handout.04", kind: "handout", label: "Handout 04 — anotações", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 04 - Anotações Arqueológicas.jpg" } },
    { id: "actOne.handout.05a", kind: "handout", label: "Handout 05A — conversa", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 05A - Conversa Grupo.png" } },
    { id: "actOne.handout.05b", kind: "handout", label: "Handout 05B — conversa", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 05B - Conversa Alan.png" } },
    { id: "actOne.handout.05c", kind: "handout", label: "Handout 05C — conversa", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 05C - Conversa Victor.png" } },
    { id: "actOne.handout.06", kind: "handout", label: "Handout 06 — estante", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 06 - Estante de Livros.jpg" } },
    { id: "actOne.handout.07", kind: "handout", label: "Handout 07 — pôster", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 07 - Pôster Lutadores de Rua.jpg" } },
    { id: "actOne.handout.08", kind: "handout", label: "Handout 08 — pôster", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 08 - Pôster Unidos do Invisível Futebol Clube.jpg" } },
    { id: "actOne.handout.09", kind: "handout", label: "Handout 09 — pôster", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 9 - Pôster Eric Tufão 3 - A Explosão Explosiva.jpg" } },
    { id: "actOne.handout.10", kind: "handout", label: "Handout 10 — imagem", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 10 - Thunderland 2008.jpg" } },
    { id: "actOne.handout.11", kind: "handout", label: "Handout 11 — RG", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 11 - RG de Alan.jpg" } },
    { id: "actOne.handout.12a", kind: "handout", label: "Handout 12A — e-mail", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 12A - E-mail de Gustavo 1.png" } },
    { id: "actOne.handout.12b", kind: "handout", label: "Handout 12B — e-mail", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 12B - Email de Gustavo 2.png" } },
    { id: "actOne.handout.12c", kind: "handout", label: "Handout 12C — e-mail", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 12C - E-mail de Gustavo 3.png" } },
    { id: "actOne.handout.13", kind: "handout", label: "Handout 13 — fotografia", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 13 - Cadáver de Gustavo.jpg" } },
    { id: "actOne.handout.14", kind: "handout", label: "Handout 14 — fotografia", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Handouts/Handout 14 - Foto de aniversário.jpg" } },
    { id: "actOne.music.01", kind: "music", label: "Música 01 — porão", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Músicas/Música 01 - O Porão.mp3" } },
    { id: "actOne.music.02", kind: "music", label: "Música 02 — ídolo", source: { act: "actOne", originalEntryPath: "Arquivos para o público - Ato I/Músicas/Música 02 - O Ídolo.mp3" } },
    { id: "actTwo.basement.map", kind: "map", label: "Porão — Ato II", source: { act: "actTwo", originalEntryPath: "Mapa/Mapa 01 - O Porão.jpg" } },
    { id: "actTwo.val.portrait", kind: "portrait", label: "Val — retrato", source: { act: "actTwo", originalEntryPath: "Tokens/Personagem - Val.png" } },
    { id: "actTwo.val.token", kind: "token", label: "Val — token", source: { act: "actTwo", originalEntryPath: "Tokens/Token - Val.png" } },
    { id: "actTwo.raven.portrait", kind: "portrait", label: "Raven — retrato", source: { act: "actTwo", originalEntryPath: "Tokens/Personagem - Raven.png" } },
    { id: "actTwo.raven.token", kind: "token", label: "Raven — token", source: { act: "actTwo", originalEntryPath: "Tokens/Token - Raven.png" } },
    { id: "actTwo.antonio.portrait", kind: "portrait", label: "Antônio — retrato", source: { act: "actTwo", originalEntryPath: "Tokens/Personagem - Antônio.png" } },
    { id: "actTwo.antonio.token", kind: "token", label: "Antônio — token", source: { act: "actTwo", originalEntryPath: "Tokens/Token - Antônio.png" } },
    { id: "actTwo.amanda.portrait", kind: "portrait", label: "Amanda — retrato", source: { act: "actTwo", originalEntryPath: "Tokens/Personagem - Amanda.png" } },
    { id: "actTwo.amanda.token", kind: "token", label: "Amanda — token", source: { act: "actTwo", originalEntryPath: "Tokens/Token - Amanda.png" } },
    { id: "actTwo.heitor.portrait", kind: "portrait", label: "Heitor — retrato", source: { act: "actTwo", originalEntryPath: "Tokens/Personagem - Heitor.png" } },
    { id: "actTwo.heitor.token", kind: "token", label: "Heitor — token", source: { act: "actTwo", originalEntryPath: "Tokens/Token - Heitor.png" } },
    { id: "actTwo.handout.01.print", kind: "handout", label: "Handout 01 — impressão", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 01 - Compendium Playtest para impressão.pdf" } },
    { id: "actTwo.handout.01.fillable", kind: "handout", label: "Handout 01 — preenchível", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 01 - Compendium Playtest preenchível.pdf" } },
    { id: "actTwo.handout.02a", kind: "handout", label: "Handout 02A — laser", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 02A - Laser Porão.jpg" } },
    { id: "actTwo.handout.02b", kind: "handout", label: "Handout 02B — laser", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 02B - Laser Sala Secreta.jpg" } },
    { id: "actTwo.handout.03", kind: "handout", label: "Handout 03 — fotografia", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 03 - Foto do Altar de Madeira.png" } },
    { id: "actTwo.handout.04", kind: "handout", label: "Handout 04 — fotografia", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 04 - Foto Dentro do Depósito B.png" } },
    { id: "actTwo.handout.05", kind: "handout", label: "Handout 05 — imagem", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 05 - Ritual de Alterar Memória.jpg" } },
    { id: "actTwo.handout.06", kind: "handout", label: "Handout 06 — fotografia", source: { act: "actTwo", originalEntryPath: "Handouts/Handout 06 - Foto do Freezer.png" } },
  ],
  handouts: [
    { id: "actOne.handout.01", act: "actOne", assetId: "actOne.handout.01", label: "Handout 01 — conversa", pageType: "image" },
    { id: "actOne.handout.02", act: "actOne", assetId: "actOne.handout.02", label: "Handout 02 — símbolo", pageType: "image" },
    { id: "actOne.handout.03", act: "actOne", assetId: "actOne.handout.03", label: "Handout 03 — RG", pageType: "image" },
    { id: "actOne.handout.04", act: "actOne", assetId: "actOne.handout.04", label: "Handout 04 — anotações", pageType: "image" },
    { id: "actOne.handout.05a", act: "actOne", assetId: "actOne.handout.05a", label: "Handout 05A — conversa", pageType: "image" },
    { id: "actOne.handout.05b", act: "actOne", assetId: "actOne.handout.05b", label: "Handout 05B — conversa", pageType: "image" },
    { id: "actOne.handout.05c", act: "actOne", assetId: "actOne.handout.05c", label: "Handout 05C — conversa", pageType: "image" },
    { id: "actOne.handout.06", act: "actOne", assetId: "actOne.handout.06", label: "Handout 06 — estante", pageType: "image" },
    { id: "actOne.handout.07", act: "actOne", assetId: "actOne.handout.07", label: "Handout 07 — pôster", pageType: "image" },
    { id: "actOne.handout.08", act: "actOne", assetId: "actOne.handout.08", label: "Handout 08 — pôster", pageType: "image" },
    { id: "actOne.handout.09", act: "actOne", assetId: "actOne.handout.09", label: "Handout 09 — pôster", pageType: "image" },
    { id: "actOne.handout.10", act: "actOne", assetId: "actOne.handout.10", label: "Handout 10 — imagem", pageType: "image" },
    { id: "actOne.handout.11", act: "actOne", assetId: "actOne.handout.11", label: "Handout 11 — RG", pageType: "image" },
    { id: "actOne.handout.12a", act: "actOne", assetId: "actOne.handout.12a", label: "Handout 12A — e-mail", pageType: "image" },
    { id: "actOne.handout.12b", act: "actOne", assetId: "actOne.handout.12b", label: "Handout 12B — e-mail", pageType: "image" },
    { id: "actOne.handout.12c", act: "actOne", assetId: "actOne.handout.12c", label: "Handout 12C — e-mail", pageType: "image" },
    { id: "actOne.handout.13", act: "actOne", assetId: "actOne.handout.13", label: "Handout 13 — fotografia", pageType: "image" },
    { id: "actOne.handout.14", act: "actOne", assetId: "actOne.handout.14", label: "Handout 14 — fotografia", pageType: "image" },
    { id: "actTwo.handout.01.print", act: "actTwo", assetId: "actTwo.handout.01.print", label: "Handout 01 — impressão", pageType: "pdf" },
    { id: "actTwo.handout.01.fillable", act: "actTwo", assetId: "actTwo.handout.01.fillable", label: "Handout 01 — preenchível", pageType: "pdf" },
    { id: "actTwo.handout.02a", act: "actTwo", assetId: "actTwo.handout.02a", label: "Handout 02A — laser", pageType: "image" },
    { id: "actTwo.handout.02b", act: "actTwo", assetId: "actTwo.handout.02b", label: "Handout 02B — laser", pageType: "image" },
    { id: "actTwo.handout.03", act: "actTwo", assetId: "actTwo.handout.03", label: "Handout 03 — fotografia", pageType: "image" },
    { id: "actTwo.handout.04", act: "actTwo", assetId: "actTwo.handout.04", label: "Handout 04 — fotografia", pageType: "image" },
    { id: "actTwo.handout.05", act: "actTwo", assetId: "actTwo.handout.05", label: "Handout 05 — imagem", pageType: "image" },
    { id: "actTwo.handout.06", act: "actTwo", assetId: "actTwo.handout.06", label: "Handout 06 — fotografia", pageType: "image" },
  ],
} as const satisfies AdventureDefinition;

export type PlaytestAlphaAssetId = (typeof PLAYTEST_ALPHA_ADVENTURE.assets)[number]["id"];
